version: "2"
services:
    db:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=api
            - POSTGRES_USER=symfony
            - POSTGRES_PASSWORD=symfony
        volumes:
            - ./data:/var/lib/postgresql/data:cached
        ports:
            - 5432:5432
    php:
        build: ./archi/php-fpm
        ports:
            - 9000:9000
        volumes:
            - ./api:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - db
            - rabbitmq
    nginx:
        build: ./archi/nginx
        ports:
            - 8007:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_ERLANG_COOKIE: "SECRET"
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - 15672:15672
            - 5672:5672
        volumes:
            - ./archi/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:cached
            - ./archi/rabbitmq/setup.sh:/etc/rabbitmq/setup.sh
    wsb:
        build: ./wsb
        environment:
            WAIT_HOSTS: rabbitmq:5672
        volumes:
          - ./wsb:/go/src/github.com/qneyrat/wsb:cached
        ports:
          - 4000:4000
        links:
          - rabbitmq
