api_login_check:
    path: /login_check

user:
    type:     annotation
    resource: App\Controller\UserController

conversation:
    type:     annotation
    resource: App\Controller\ConversationController